config/routes.rb
ComponentOfPartx::Engine.routes.draw do
  resources :components
  
  root :to => 'components#index'

end

app/models/component_of_partx/component.rb
module ComponentOfPartx
  class Component < ActiveRecord::Base
    attr_accessor :part_name, :part_id_noupdate
    attr_accessible :last_updated_by_id, :name, :part_id, :qty, :spec, :unit, :production_start_date, :production_finish_date, :ontime_indicator,
                    :part_name,
                    :as => :role_new
    attr_accessible :last_updated_by_id, :name, :qty, :spec, :unit, :production_start_date, :production_finish_date,
                    :part_name, :part_id_noupdate, :ontime_indicator,
                    :as => :role_update   
                    
    belongs_to :part, :class_name => ComponentOfPartx.part_class.to_s
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    
    validates_presence_of :name, :qty, :unit 
    validates :part_id, :numericality => {:greater_than => 0, :only_integer => true}
    validates :qty, :numericality => {:greater_than_or_equal_to => 0, :only_integer => true}
    validates :name, :uniqueness => {:scope => :part_id, :case_sensitive => false, :message => I18n.t('No duplicate name')}  
    validate :dynamic_validate 
    
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate', 'component_of_partx')
      eval(wf) if wf.present?
    end           
  end
end

app/controllers/component_of_partx/application_controller.rb
module ComponentOfPartx
  class ApplicationController < ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    
    before_filter :require_signin
    before_filter :max_pagination 
    before_filter :check_access_right 
    before_filter :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_filter :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right
    before_filter :view_in_config?
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination')
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
  end
end

app/controllers/component_of_partx/components_controller.rb
require_dependency "component_of_partx/application_controller"

module ComponentOfPartx
  class ComponentsController < ApplicationController
    before_filter :require_employee
    before_filter :load_parent_record
        
    def index
      @title = t('Components')
      @components = params[:component_of_partx_components][:model_ar_r]  #returned by check_access_right
      @components = @components.where(:part_id => @part.id) if @part       
      @components = @components.page(params[:page]).per_page(@max_pagination) 
      @erb_code = find_config_const('component_index_view', 'component_of_partx')
    end
  
    def new
      @title = t('New Component')
      @component = ComponentOfPartx::Component.new()
      @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
      @erb_code = find_config_const('component_new_view', 'component_of_partx')
    end
  
    def create
      @component = ComponentOfPartx::Component.new(params[:component], :as => :role_new)
      @component.last_updated_by_id = session[:user_id]
      if @component.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        @part = ComponentOfPartx.part_class.find_by_id(params[:component][:part_id]) if params[:component].present? && params[:component][:part_id].present?
        @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
        @erb_code = find_config_const('component_new_view', 'component_of_partx')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update Component')
      @component = ComponentOfPartx::Component.find_by_id(params[:id])
      @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
      @erb_code = find_config_const('component_edit_view', 'component_of_partx')
    end
  
    def update
      @component = ComponentOfPartx::Component.find_by_id(params[:id])
      @component.last_updated_by_id = session[:user_id]
      if @component.update_attributes(params[:component], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        @part = ComponentOfPartx.part_class.find_by_id(params[:component][:part_id]) if params[:component].present? && params[:component][:part_id].present?
        @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
        @erb_code = find_config_const('component_edit_view', 'component_of_partx')
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    protected
    def load_parent_record
      @part = ComponentOfPartx.part_class.find_by_id(params[:part_id]) if params[:part_id].present?
      @part = ComponentOfPartx.part_class.find_by_id(ComponentOfPartx::Component.find_by_id(params[:id]).part_id) if params[:id].present?
    end
  end
end

app/helpers/component_of_partx/application_helper.rb
module ComponentOfPartx
  module ApplicationHelper
  end
end

app/helpers/component_of_partx/components_helper.rb
module ComponentOfPartx
  module ComponentsHelper
  end
end

app/views/component_of_partx/components/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
  <% else %>
<%= simple_form_for @component do |f| %> 
  <%= f.input :part_id_noupdate, :label => t('Part#'), :readonly => true, :input_html => {:value => @part.id} %>
  <%= f.input :part_name, :label => t('Part Name'), :readonly => true, :input_html => {:value => @part.name} %>
  <%= f.input :name, :label => t('Component Name') %>  
  <%= f.input :spec, :label => t('Spec'), :input_html => {:rows => 1}, :readonly => readonly?(@component, 'spec') %>
  <%= f.input :qty, :label => t('Qty'), :readonly => readonly?(@component, 'qty') %>
  <%= f.input :unit, :label => t('Qty Unit'), :collection => @qty_unit, :readonly => readonly?(@component, 'unit') %>
  <%= f.input :production_start_date, :label => t('Production Start Date'), :as => :string %>
  <%= f.input :production_finish_date, :label => t('Production Finish Date'), :as => :string %>  
  <%= f.input :ontime_indicator, :label => t('On Time'), :collection => [[t('Green - on time'),'green'], [t('Yellow - little hehind'), 'yellow'], [t('Red - late'), 'red']] %>
    
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>  

<% end %>

app/views/component_of_partx/components/_form_list.html.erb
 <% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
  <% else %>
<div class="pagination"><%= will_paginate models %></div>
    <table class="table table-striped">
		<tr>
			<th>#</th>
			<th><%= t('Part Name') %></th>
			<th><%= t('Component Name') %></th>
			<th><%= t('Spec') %></th>
			<th><%= t('Qty/Unit') %></th>
			<th><%= t('On Time') %></th>
			<th><%= t('Production Start Date') %></th>
			<th><%= t('Production Finish Date') %></th>	
			<th><%= t('Last Updated By') %></th>
			<th></th>
			<th></th>
			
		</tr>
		<% models.each do |r| %>
		  <tr>
		  	<td><%= prt(r, :id) %></td>		  	
		  	<td><%= link_to r.part.name, SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(ComponentOfPartx.show_part_path))}" %></td>
		  	<td><%= prt(r, :name) %></td>
			<td><%= prt(r, :spec) %></td>
			<td><%= prt(r, :qty) %>/<%= prt(r, :unit) %></td>
			<td><%= image_tag('component_of_partx/'+RED_GREEN_YELLOW_CLS[r.ontime_indicator], size: '23x23') if r.ontime_indicator.present? %></td>
			<td><%= r.production_start_date.strftime("%Y/%m/%d") if r.production_start_date.present? %></td>
			<td><%= r.production_finish_date.strftime("%Y/%m/%d") if r.production_finish_date.present? %></td>
			<td><%= prt(r, 'last_updated_by.name') %></td> 
			<td><%= link_to t('QC Record'), SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(commonx.logs_path(:resource_name => 'component_of_partx/components', resource_id: r.part_id, :subaction => 'component'))}", :class => BUTTONS_CLS['action']   %></td>
			<td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{edit_component_path(r, :parent_record_id => r.part_id, :parent_resource => ComponentOfPartx.part_class.to_s.underscore.pluralize)}", :class => BUTTONS_CLS['action']  if has_action_right?('update', params[:controller], r) %></td>
		  </tr>
		<% end %>
	</table>
	
	<table class="table table-striped">
	  <tr>
	    <th>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
	    	
	    </th>
	  </tr>
	</table>
	
	<% end %>
	

app/views/component_of_partx/components/_form_new.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
  <% else %>
<%= simple_form_for @component do |f| %> 
      <%= f.input :part_id, :label => t('Part#'), :readonly => true, :input_html => {:value => @part.id} %> 
      <%= f.input :part_name, :label => t('Part Name'), :readonly => true, :input_html => {:value => @part.name} %>
	  <%= f.input :name, :label => t('Component Name') %>  
	  <%= f.input :spec, :label => t('Spec'), :input_html => {:rows => 1} %>
	  <%= f.input :qty, :label => t('Qty') %>
	  <%= f.input :unit, :label => t('Qty Unit'), :collection => @qty_unit, :include_blank => true %>
	  <%= f.input :production_start_date, :label => t('Production Start Date'), :as => :string %>
	  <%= f.input :production_finish_date, :label => t('Production Finish Date'), :as => :string %>
	  <%= f.input :ontime_indicator, :label => t('On Time'), :collection => [[t('Green - on time'),'green'], [t('Yellow - little hehind'), 'yellow'], [t('Red - late'), 'red']] %>
  
	  
	  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
	  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>
  
<% end%>

app/views/component_of_partx/components/create.html.erb
<h4>Projects#create</h4>
<p>Find me in app/views/task_definitions/create.html.erb</p>

app/views/component_of_partx/components/edit.html.erb
<div id="main_body">
<h4><%=t('Edit Component Info') %></h4>
 
<%= render 'form'  %>
 
</div>
  
 

app/views/component_of_partx/components/index.html.erb
<div id="main_body">
	<h4><%=t('Components') %></h>
 
	<%= render partial: 'form_list', locals: {models: @components} %>
 
</div>

app/views/component_of_partx/components/new.html.erb
<div id="main_body">
<h4><%=t('New Component') %></h4>

<%= render 'form_new' %>

</div>

app/views/component_of_partx/components/update.html.erb
<h1>EventTasks#update</h1>
<p>Find me in app/views/event_taskx/event_tasks/update.html.erb</p>